### PR TITLE
Add show, create, update paths for foods

### PR DESCRIPTION
**Pull request by glassjoseph**

### CODE REVIEW

**Comment by valerietrudell** [comment]
@neight-allen Okay so a few questions:

Do we need foods_test db and meals_test db?
if so for the migration we don’t make one do we need to?  

We are just having problems with testing the models we've set up

**Comment by neight-allen** [comment]
@valerietrudell Typically, your table names are the same across databases. So you'll have a `quantified_self` and a `quantified_self_test` database, but both of them will have a `meals` and a `foods` table in them. Does that help?

**Comment by valerietrudell** [comment]
@neight-allen so we need to have 6 migrations in total 3 for quantified_self and 3 for _test?. Because I'm having trouble with the testing. When I do run tests it says that foods doesn't exist.

**Comment by neight-allen** [comment]
@valerietrudell 

1. You would want to have the same migrations for both. Knex gives you different seed files for each environment, but you run the same migrations on multiple environments. More details if you run `knex -h` in the terminal.
2. You don't strictly need a separate migration for each table, but you can organize them into separate migrations if you like. The example seed file in the SQL in Node lesson has an example of running multiple SQL statements in one file.

**Pull request merged**
